<MainGrid>
    cols: 1
    gameGrid: []
    moveTiles: []
    staticTiles: []
    sizeTile: 30
    lastMove: ""
    clockEvent: None
    on_kv_post: root.setup()
    on_size: root.changeSize()
    Label:
        text: "Tetris"
        font_size: 30
        size_hint_y: None
        size_hint: (1, 0.2)
    BoxLayout:
        orientation: 'vertical'
        size_hint_y: None
        size_hint: (1, 0.8)
        padding: 10
        id: tetrisCanvas